#!/usr/bin/env bash
# This wrapper check that the current opam switch is consistent with the src/opam.export file before calling dune.
set -e
pushd "$(dirname "$0")/check_opam_switch/"
dune build checked_switch
popd
exec dune "$@"

